# Generated by Django 5.0.1 on 2024-04-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=15)),
                ('k_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=50)),
                ('narx', models.PositiveIntegerField()),
                ('litr', models.PositiveIntegerField()),
                ('batafsil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Adminlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('yosh', models.IntegerField()),
                ('ish_vaqti', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=100)),
                ('qarz', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qachon', models.DateTimeField()),
                ('miqdori', models.PositiveIntegerField()),
                ('umumiy_narxi', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adminlik')),
                ('yetkazib_berish_haydovchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.haydovchi')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mijoz')),
                ('suv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.suv')),
            ],
        ),
    ]
