# Generated by Django 5.0.1 on 2024-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suv',
            name='litr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suv',
            name='narx',
            field=models.FloatField(),
        ),
    ]
